### ISSUE TITLE
[Bug] Repository list crash

### ISSUE THREAD

**Issue by C10udburst** [GooseMod/GooseMod#52]
**Describe the bug**
Pressing the repository list button causes a crash in web client

**To Reproduce**

https://user-images.githubusercontent.com/18114966/138947201-5cae802d-8785-41df-819f-19ad1023077c.mp4

**Expected behavior**
not to crash lol

**Screenshots**
above

**GooseMod info:**
`goosemod.genDebugInfo()` output:
```yaml
Discord:
Client: web
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Release Channel: stable
Other Mods: 

GooseMod:
GM Version: 12.2 (de3e184e51904d7bd4671afb8eeff739739bd719)
GM Branch: null
GM Extension Version: 1.2.1
GM Storage Impl: Extension
Modules: Fucklytics, Custom CSS, Webhook Tags, Better Message Deletion, Dev Mode, Web Right Click, Show All Activities, CreArts | Friends-Grid, Discolored, Better Badges, Gradient Button V2, De-Nitro, Hidden Channels, TwemojiEverywhere, Discord Debug, Silent Typing, Pop!, User Popout Creation Date, Spotify Crack, FreeNitro
```

**Discord info:**
```
Stable 102471 (e7e6e45)
Windows 10 64-Bit
```
**Other info:**
 - Other Mods: None

**Additional context**
